FROM adoptopenjdk:11-hotspot
RUN apt-get update
#insall curl
RUN apt-get install -y curl wget gnupg git net-tools

#Install Maven
RUN apt-get -y install maven

#Install the Microsoft package repository GPG key, to validate package integrity
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

#Set up the .NET development source list before doing an APT update.
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

#Run apt update
RUN apt-get update

#Install the Core Tools package
RUN apt-get install -y azure-functions-core-tools
ENTRYPOINT [ "bash" ]